Added a note to README about needing an AUTH_SECRET env var and warning to not commit this secret to repo
qsib-cbie/asset-tracking-api pull request #4
Opened 2020-11-09 23:36 UTC by xunchuan-liu

2020-11-09 23:36 UTC, xunchuan-liu commented on README.md
> +    * You need to generate a random string at least **48** bytes long for the AUTH_SECRET var in local development. Be sure this secret does **not** get commited anywhere in the repo.
Editing .env variables to include AUTH_SECRET. Note to not commit this secret to any public repo.

2020-11-10 00:05 UTC, trueb2 commented on README.md
> +    * You need to generate a random string at least **48** bytes long for the AUTH_SECRET var in local development. Be sure this secret does **not** get commited anywhere in the repo.
For things that produce the proper error message and check, I'd rather not add it to the README. Information not included in the error message that was produced was how to create a good/valid AUTH_SECRET.

2020-11-12 19:07 UTC, trueb2 requested changes
Add suggestions for .env documentation.

2020-11-12 19:07 UTC, trueb2 commented on README.md
>  RUST_LOG=asset_api=trace,rest_api=trace,actix=trace,actix_web=debug,diesel_migrations=trace
```suggestion
RUST_LOG=qsib_asset=trace,info
```

2020-11-12 19:07 UTC, trueb2 commented on README.md
> +    * You need to generate a random string at least **48** bytes long for the AUTH_SECRET var in local development. Be sure this secret does **not** get commited anywhere in the repo.
```suggestion
    * `AUTH_SECRET` must be defined. Generate a random string at least **48** bytes long for local development.
    * Do **not** commit sensitive environment variables or tokens.
```

2020-11-12 19:07 UTC, trueb2 approved these changes

2020-11-12 19:07 UTC, merged